@startuml

entity StockSageWebsite {
    * Frontend website provided by AWS S3 and Cloudfront
}

entity StockSageServiceLambda {
  * Dynamic and Responsive HTTP Calls over AWS Lambda
}

class StockSageActivityProvider {
  *GetRecentQueriesActivity
  *GetSavedQueriesActivity
  *SaveQueryActivity
  *UnsaveQueryActivity
  *UpdateTitleAndContentActivity
}

entity AlphaAdvantageService {
  * Provides Stock Market Data from https://www.alphavantage.co/
}

class QueryDao {
  - DynamoDbMapper
}

entity DynamoDb-Queries-Table {
}


StockSageWebsite --> StockSageServiceLambda

ActivityProvider <-- StockSageServiceLambda
ActivityProvider --> QueryDao
ActivityProvider --> StockApiDao
StockApiDao --> AlphaAdvantageAPI
StockApiDao <-- AlphaAdvantageAPI

UserDao --> DynamoDb
QueryDao --> DynamoDb
NoteDao --> DynamoDb

@enduml
